### ISSUE TITLE
Wallet file saved in the Electron Cash working directory

### ISSUE THREAD

**Issue by sickpig** [Bitcoin-ABC/ElectrumABC#10]
Please rename E-ABC working directory to avoid confusion and potential problem for users that install Electrum Cash and E-ABC on the same machine.  

edit: I've reproduced the problem on macos and the EC workdir was actually a symlink

**Comment by PiRK** [comment]
The working directory has been renamed. But I managed to reproduce a weird behavior by editing my` .config` file to have paths point to the `.electron-cash` dir. A newly created wallet was created in the EC dir. 

This is something that could happen for the alpha and beta releases, before commit https://github.com/Bitcoin-ABC/ElectrumABC/commit/c2fdb1c1381b2fcf0c95e66f9a7dc11b5b880ffa 
Maybe this is what you are experiencing.

I will have a look at the code and try to find out why the paths to previous wallets affect the newly created wallets as well.

**Comment by PiRK** [comment]
The `get_new_wallet_path` (https://github.com/Bitcoin-ABC/ElectrumABC/blob/master/electroncash_gui/qt/__init__.py#L569) calls a `get_wallet_folder` method which uses in turns `config.get_wallet_path`, which seems to return the path to the current default wallet. The new wallet will be saved wherever the current default-wallet is saved.

The "default wallet" seems to be the last wallet that was opened (including external wallets open via the File -> Open menu).

It think a better behavior would be to either always create the new wallet in the normal user dir, or ask the user. Unless the user started the program with a different wallet path explicitly requested on the command line.

**Comment by sickpig** [comment]
> This is something that could happen for the alpha and beta releases, before commit [c2fdb1c](https://github.com/Bitcoin-ABC/ElectrumABC/commit/c2fdb1c1381b2fcf0c95e66f9a7dc11b5b880ffa)
> Maybe this is what you are experiencing.

![Screenshot 2020-11-26 at 17 54 04](https://user-images.githubusercontent.com/1469203/100376832-7aa25100-3010-11eb-84cf-e0a5b600a3a8.png)

**Comment by sickpig** [comment]
> It think a better behavior would be to either always create the new wallet in the normal user dir, or ask the user. Unless the user started the program with a different wallet path explicitly requested on the command line.

agreed
