### ISSUE TITLE
Network server for ABC BCHA no longer available?

### ISSUE THREAD

**Issue by ONEGR8AV8R** [Bitcoin-ABC/ElectrumABC#110]
Hi,
I used Electron Cash to split off BCHA from my BCHN five months ago.  Shortly after the split I sent my BCHN back to another wallet.  However, I wanted to now send my BCHA coin to the ViaWallet.  My understanding would be that within the Electron Cash desktop I would select a server on the ABC network and then I could send those coins, but the electrom abc server is no longer available.  I input it manually but it instantly popped up in the "banned" list.  Are there no longer ABC servers available or am I going about this wrong?  Although my split ABC coin does not show up in Electron cash ABC I believe it would if I was able to select a network server, my coin does show up as received on the ABC address qzlryncqf8s6sdmrkm2h78xj2wfumg3lyqrx7ck44h.  Any help on this from a knowledgeable BCHA person?

**Comment by chianti60** [comment]
Bonjour , il m'est arrivé le même problème avec la séparions de mes BCH , je recherche aussi une aide

**Comment by PiRK** [comment]
Electron Cash no longer supports Electrum ABC servers and vice-versa. Both wallets now have implemented a checkpoint post fork, to make sure no-one accidentally ends-up on the wrong network and spends the wrong currency.

You can still split your coins the same way as before by running Electrum ABC and Electron Cash side by side. Just import the same wallet file in both softwares (Electrum ABC automatically import your existing Electron Cash wallets, the first time you import it).
