### ISSUE TITLE
open failed error

### ISSUE THREAD

**Issue by GonzaloMoreno** [Bitcoin-ABC/ElectrumABC#134]
Hi: I am interested in moving my XEC from elctrumabc but whe I try to do it  an error of open failed appears what coul I do? [
<img width="1646" alt="Captura de Pantalla 2021-09-19 a la(s) 10 43 35 p  m" src="https://user-images.githubusercontent.com/7675634/133955189-abbb5c1c-7697-43eb-9478-c4bb12254638.png">
](url)

**Comment by PiRK** [comment]
Is that a Mac? Could you try Electrum ABC 5.0.0 and tell me if it makes a difference?

**Comment by PiRK** [comment]
V5.0.2 fixes an issue that causes a crash with MacOS. You can try that. If it does not work feel free to reopen this issue by providing more information to help with troubleshooting the issue.
