### ISSUE TITLE
Keys and Hashes 

### ISSUE THREAD

**Issue by roabhi** [Bitcoin-ABC/ElectrumABC#17]
Hi there and thanks for working on ElectrumABC!.

Is there a plce where could I find the right checksums and keys for the release?

Thanks a lot.

**Comment by PiRK** [comment]
This is something that I plan to  look into implementing in the next release, which is hopefully very soon.

**Comment by PiRK** [comment]
I have added the sha chechsums and signed the binaries for the 4.3.1 release. I still need to find a sensible way of distributing the key. Bundling it with the repository does not help users very much, in terms of security.

**Comment by PiRK** [comment]
Closed by b7b9cc8328537fc5d6530deff93a29cb934a72c5

The signatures and hashes are available  with the release files: https://github.com/Bitcoin-ABC/ElectrumABC/releases/tag/4.3.1
The key is here: https://github.com/Bitcoin-ABC/ElectrumABC/blob/master/pubkeys/PiRK.asc

**Comment by roabhi** [comment]
Thanks a lot for your work
