### ISSUE TITLE
Wallet automatically opens Bitcoin Cash Electron wallet file, fresh install.

### ISSUE THREAD

**Issue by Morsine** [Bitcoin-ABC/ElectrumABC#175]
Hi.
I've recently installed this wallet, and noticed it didn't ask me to create a new wallet, and just asked me to open my already existing wallet! (But I don't have a wallet!!)
So I've entered the password to the other wallet that I have (Bitcoin Cash). and it opened up!
the addresses it shows in the address tab start with q
and the seed is the same as Bitcoin Cash wallet.
but why?
shouldn't the wallet access its own folder:
%USER%\appdata\roaming\ElectrumABC\wallets\default_wallet
instead of a folder related to another wallet:
%USER%\appdata\roaming\electroncash\wallets\default_wallet

Edit: I noticed it copied the wallet file from the electroncash over to the electrumabc.

**Comment by PiRK** [comment]
Yes, this is something we did to help with the coin splitting shortly after the fork. I will probably deactivate this feature soon.

**Comment by Morsine** [comment]
Thank you for replying @PiRK . Forgive me for asking this newbie question.. is it okay to keep using this wallet that was initially created by the bitcoin cash wallet after the fork?

**Comment by PiRK** [comment]
I strongly recommend doing this procedure to properly split your XEC and BCH: 
https://blog.bitcoinabc.org/2020/11/25/how-to-split-your-bch-bchn-and-bcha-coins-using-electrum-abc-and-electron-cash/

If you do not do this, the risk is that any transaction that you send on either one of these blockchains will also happen on the other one. So when you think that you are only sending BCH, you might also be sending XEC to the same address.

**Comment by Morsine** [comment]
> 

Thank you, I've done what has been described in the link you've sent.
Since I don't have any bitcoin cash, I only did the second part for the XEC.
Thank you agian.!
