### ISSUE TITLE
Zero balanced transactions

### ISSUE THREAD

**Issue by blackstake22** [Bitcoin-ABC/ElectrumABC#227]
From 20.07.22 My transactions arrived with +0,00 value. I had 42 transactions since then with approx. 44.000 XEC
Could you please help me what can I do, how can I see this amounts on my account ?

THX in advance!

**Comment by PiRK** [comment]
Hi. I will have a look soon at the software. I experienced a similar issue yesterday, maybe our issues are related.

Could you tell me some more information:
-  which version of Electrum ABC is installed?
- what OS are you using?
- is your wallet a standard wallet, or a hardware wallet, or a watch-only wallet (xpub)?

**Comment by PiRK** [comment]
The issue seems to be caused by one of the electrum servers malfunctioning.

Could you try to go to menu `Tools` > `Network`, right click on the `electrum.bitcoinabc.org` server and select "Use as server". And then, go to menu `Wallet` > `Rebuild History`

**Comment by PiRK** [comment]
The faulty server has been fixed (the node got restarted recently without the `-txindex=1` parameter). So the fix is now simply: 
Wallet > Rebuild History
