### ISSUE TITLE
who's pubkey for appimage?

### ISSUE THREAD

**Issue by ElectrumBSV** [Bitcoin-ABC/ElectrumABC#32]
Electrum ABC appimage is signed by who and where do i get his pubkey?

**Comment by PiRK** [comment]
I just uploaded it here: http://keyserver.ubuntu.com/pks/lookup?search=pierrekn%40gmail.com&fingerprint=on&op=index
It should propagate to other key servers soon.

We are just starting this process of signing binaries, so right now I'm aware that it is not worth much.

**Comment by ElectrumBSV** [comment]
thank you
